### ISSUE TITLE
ClientComm 1.0 should update live

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#3]
**User story:**
- As a PO
- I want ClientComm to automatically update with new information
- So that I don’t have to guess and refresh the page constantly
 
**Requirements:**
- Socket connection to server
- Note: this is _strongly desired_ but _not absolutely critical_. If, in trying to implement it, it feels overwhelming or overly-complicated, let’s reassess. 

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.50s262gi6gx7

**Comment by tdooner** [comment]
Oooh ooooh this sounds fun.

A couple thoughts. ActionCable (backed by Redis) sounds like a great way to do this idiomatically since we're on Rails 5.x. I haven't tried this though, so I don't know how it works in practice. (But I would be interested in pairing on this since I haven't tried it yet!)

Speaking of Redis, bringing Redis in as a dependency is a robust way to schedule background jobs, which we will certainly eventually want to do. It can even be used for caching. And session persistence. Truly lots of stuff! Redis is great!
